# Generated by Django 6.0 on 2025-12-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='url',
            new_name='video_url',
        ),
    ]
